### ISSUE TITLE
No my_script.py file..

### ISSUE THREAD

**Issue by ghost** [WulffHunter/log_generator#2]
Hi, 

Can you explain me how to use this repository to parse my custom log.

**Comment by WulffHunter** [comment]
Hello Vijay,

Thank you for checking out our repository! This repository doesn't include the models to actually parse custom logs, but rather the generator to create fake logs in an ingestible format for training and files to clean publicly available log files into that same format. Both of the sub-directories in this repository should have detailed instructions on how to run the respective scripts: if either is unclear, please let me know and I'd be happy to clarify.

Please let me know if this helps!

Best,
Jared
